title: Documentation API Partenaires
author: MyUnisoft
theme: jekyll-theme-cayman
social-network-links:
  email: "c.mandrilly@myunisoft.fr"
  facebook: MyUnisoft
  github: MyUnisoft
  twitter: MyUnisoft